# A generic, single-database configuration.

[alembic]
# path to migration scripts
script_location = alembic

sqlalchemy.url = ${DATABASE_URL}

# template for new migration scripts
file_template = %%(rev)s_%%(slug)s

# timezone for revision timestamps
timezone =

# max length of characters to apply to the
# "slug" field
# slug_max_length = 40

# set to 'true' to each migration script set up its own logging.
# append_database_name = false

# set to 'true' to have Alembic guess at an appropriate
# revision number for autogeneration
# revision_range_for_autogen = 2

# services - somemigrationengine:main
# services =

# Post-write hooks are Python functions that are run
# after a migration script is generated.
# post_write_hooks =

# The starting revision for the new alembic environment.
# This is typically 'base' but can be set to a specific revision.
# starting_revision = base

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
